" Vim设置
" author:     yannsun
" updateDate: 2017-4-2

"Vundle设置
set nocompatible              " 去除VI一致性,必须
filetype off                  " 必须

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree' 	  " nerdtree插件
Plugin 'mhinz/vim-startify'  	  " vim首页美化插件
Plugin 'majutsushi/tagbar'   	  " 展示类和方法结构插件
Plugin 'dracula/vim'			  " 主题
Plugin 'fatih/vim-go'			  " golang
Plugin 'Yggdroot/indentLine'      " 缩进标线 
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'ekalinin/Dockerfile.vim'  " Docker配置语法高亮
call vundle#end()            " 必须
filetype plugin indent on    " 必须 加载vim自带和插件相应的语法和文件类型相关脚本

let g:tagbar_autofocus = 1

" 基本设置
set nu 						  "显示行号
syntax on					  "语法高亮
set autoindent 				  "自动缩进
set tabstop=4		   		  "设置tab键为4个空格
set shiftwidth=4
set tags+=./tags			  "设置tags目录
set hlsearch                  "高亮搜索
set noswapfile				  "不生成swp文件
set backspace=indent,eol,start

" 编码设置
set fileencodings=utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1
set enc=utf8
set fencs=utf8,gbk,gb2312,gb18030

" 主题设置
let g:solarized_termcolors=256
syntax enable
set background=dark
colorscheme solarized
"syntax on
"colorscheme dracula

" 快捷键设置
map <F9>  :NERDTreeToggle<CR>
map <C-M> :tabnext<CR>  
map <C-N> :tabprevious<CR>  
map <F10> :TagbarToggle<CR>

